name: CMake

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "master", "develop" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: :0

jobs:
  build:
    if: contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
        - os: ubuntu-20.04
          cmake-options: -GNinja
        - os: windows-2019
        - os: macos-12
          cmake-options: -GNinja

    steps:
    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libasound2-dev libjack-jackd2-dev \
          ladspa-sdk \
          libcurl4-openssl-dev  \
          libfreetype6-dev \
          libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
          libwebkit2gtk-4.0-dev \
          libglu1-mesa-dev mesa-common-dev

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
      
    - name: Configure
      run: cmake -Bbuild ${{ matrix.cmake-options }} -DPRODUCTION_BUILD=1

    - name: Build
      run: cmake --build build --config Release

    - name: Validate
      run: bash ./validate.sh
